apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployment
  labels:
    tier: frontend
spec:
  template:
    metadata:
      name: app
      namespace: default
      labels:
        app: app
    spec:
      containers:
        - image: busybox
          command:
            - sleep
            - "3600"
          imagePullPolicy: IfNotPresent
          name: busybox
        - image: nginx
          name: nginx
      restartPolicy: Always
  replicas: 3
  selector:
    matchLabels:
      app: app